### ISSUE TITLE
Handling shadows 

### ISSUE THREAD

**Issue by mindlens** [RocketCommunicationsInc/figma-testing-library#3]
Any thoughts on how the shadow can be handled?

I was trying to use the codes, when I did a comparsion.. The figma scrrenshot came with shadow and codes have the shadow outside.. so overall the figma image was slightly smaller than the actual code..

![image](https://user-images.githubusercontent.com/43948820/215421638-d74fafde-aa8b-4563-8fe6-a481abdf84f9.png)

**Comment by mindlens** [comment]
I used a container outside for Figma and code as a wrapper and control the positioning of the component both in figma and code to be same to do exact comparisons.

**Comment by markacianfrani** [comment]
Glad ya got it workin! Sometimes it's not perfect and you need to do some adjustments like that because the way figma does things isn't also the same
